name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Puedes especificar la rama que activará el pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USER: ec2-user
          EC2_HOST: ${{ secrets.EC2_PUBLIC_IP }}
          REPO_DIR: /home/ec2-user/integracion/Integraci-n-de-plataformas
        run: |
          echo "${EC2_SSH_KEY}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
            echo ${REPO_DIR}
            cd ${REPO_DIR}
            git pull origin main
            docker-compose down
            docker-compose up -d
          EOF
          rm -f key.pem
